# config.py – BOT ELITE 2026 (VERSÃO FINAL 100% FUNCIONAL)
import datetime
import MetaTrader5 as mt5
import os
from dotenv import load_dotenv

MODE = "DEMO"
FORCE_DEMO_PROTECTION = True
CORRETORA_SUFFIX = ""

# ==================== CONTROLE SETORIAL ====================
SETORES = {
    "PETR4":"PETROLEO", "PETR3":"PETROLEO", "PRIO3":"PETROLEO", "RRRP3":"PETROLEO",
    "VALE3":"MINERIO", "GGBR4":"SIDERURGIA", "GGBR3":"SIDERURGIA", "CSNA3":"SIDERURGIA", "USIM5":"SIDERURGIA", "USIM3":"SIDERURGIA",
    "ITUB4":"BANCOS", "ITUB3":"BANCOS", "BBDC4":"BANCOS", "BBDC3":"BANCOS", "BBAS3":"BANCOS", "SANB11":"BANCOS",
    "ABEV3":"BEBIDAS", "JBSS3":"ALIMENTOS", "BRFS3":"ALIMENTOS", "MRFG3":"ALIMENTOS", "SMTO3":"ALIMENTOS", "SLCE3":"ALIMENTOS",
    "WEGE3":"INDUSTRIA", "EMBR3":"INDUSTRIA", "LEVE3":"INDUSTRIA", "TUPY3":"INDUSTRIA", "RAPT4":"INDUSTRIA", "RAPT3":"INDUSTRIA",
    "RENT3":"LOCACAO", "LCAM3":"LOCACAO", "VAMO3":"LOCACAO", "MOVI3":"LOCACAO",
    "MGLU3":"VAREJO", "LREN3":"VAREJO", "AMER3":"VAREJO", "SOMA3":"VAREJO", "ARZZ3":"VAREJO", "VIIA3":"VAREJO", "BHIA3":"VAREJO", "PCAR3":"VAREJO",
    "AZUL4":"AEREO", "GOLL4":"AEREO",
    "RAIL3":"FERROVIARIO", "RLOG3":"LOGISTICA", "LOGN3":"LOGISTICA", "JSLG3":"LOGISTICA", "HBSA3":"LOGISTICA",
    "TAEE11":"ENERGIA", "TAEE4":"ENERGIA", "CPFE3":"ENERGIA", "EQTL3":"ENERGIA", "ENBR3":"ENERGIA", "EGIE3":"ENERGIA", "NEOE3":"ENERGIA", "CMIG4":"ENERGIA",
    "HYPE3":"SAUDE", "RADL3":"SAUDE", "FLRY3":"SAUDE", "QUAL3":"SAUDE", "RDOR3":"SAUDE", "PARD3":"SAUDE",
    "LWSA3":"TECNOLOGIA", "TOTS3":"TECNOLOGIA", "POSI3":"TECNOLOGIA", "CASH3":"TECNOLOGIA", "INTB3":"TECNOLOGIA",
    "SUZB3":"PAPEL", "KLBN11":"PAPEL", "KLBN3":"PAPEL", "KLBN4":"PAPEL",
    "CRFB3":"VAREJO", "ASAI3":"VAREJO", "RAIZ4":"AGRO", "BEEF3":"AGRO",
}
MAX_PER_SETOR = 10

# ==================== FILTRO IBOV ====================
IBOV_SYMBOL = "WINZ25"
IBOV_MAX_DROP_PCT = -0.003

# ==================== ATR POSITION SIZING ====================
ATR_PERIOD = 14
ATR_MULTIPLIER = 1.5

# ==================== LISTA BASE ====================
CANDIDATOS_BASE = [
    "PETR4","PETR3","VALE3","ITUB4","ITUB3","BBDC4","BBDC3","BBAS3","ABEV3","WEGE3",
    "JBSS3","PRIO3","GGBR4","GGBR3","CSNA3","USIM5","USIM3","SUZB3","KLBN11","KLBN3",
    "BRFS3","CRFB3","RADL3","HYPE3","RENT3","LCAM3","VAMO3","POSI3","LREN3","GUAR3",
    "ASAI3","NTCO3","BEEF3","RAIZ4","AMER3","MGLU3","LWSA3","VIIA3","SOMA3","ARZZ3",
    "CYRE3","MRVE3","EZTC3","TEND3","CVCB3","AZUL4","GOLL4","CMIG4","CMIG3","CPFE3",
    "TAEE11","TAEE4","TAEE3","ENBR3","ENGI11","ENGI4","ENGI3","EGIE3","EQTL3","NEOE3",
    "CPLE6","CPLE3","TRPL4","TRPL3","CCRO3","ECOR3","TIMP3","VIVT3","RAIL3","LOGN3"
]

# ==================== CONFIGURAÇÕES PRINCIPAIS ====================
USE_FRACTIONAL = False
CAPITAL_MAX_POR_ATIVO_REAIS = 15000.0
RISCO_PORCENTO_DO_CAPITAL = 1.2

LOTE_PADRAO = 100
MAX_ASSETS_NA_TELA = 20
MAX_ASSETS_SCANEADOS = 80

MIN_MOMENTUM_UP = 0.4
MIN_VOLUME_MULTIPLIER = 1.5

EMA_FAST = 3          # ← TEM QUE TER
EMA_SLOW = 15
EMA_TENDENCIA_RAPIDA = 9    
EMA_TENDENCIA_LENTA  = 21
RSI_PERIOD = 14
RSI_OVERSOLD = 70
VOLUME_MA_PERIOD = 20

TAKE_PROFIT_PCT = 0.030
STOP_LOSS_PCT = 0.020
TRAILING_STOP_PCT = 0.007
TRAILING_ACTIVATION_PCT = 0.040
MAX_SPREAD_CENTS = 0.20

TIMEFRAME_MT5 = mt5.TIMEFRAME_M5
START_TIME = datetime.time(10, 10)
END_TIME = datetime.time(16, 50)
CHECK_INTERVAL_SLOW = 60
CHECK_INTERVAL_FAST = 0.5

os.makedirs("logs", exist_ok=True)
os.makedirs("trades", exist_ok=True)
os.makedirs("backtest", exist_ok=True)

LOG_FILE = "logs/bot_elite_2026.log"
CSV_FILE = "trades/bot_elite_2026.csv"

SCREEN_UPDATE_REQUIRED = True
CANDIDATOS_DINAMICOS = []