import datetime
import os
import MetaTrader5 as mt5

# ==================== GERAIS ====================
MODE = "DEMO"  # "REAL" ou "DEMO" — altere com cuidado
LOG_FILE = "logs/bot_elite_2026.log"
TRADES_FILE = "trades/trades_2026.csv"
METRICS_FILE = "metrics/live_metrics.json"
OPTIMIZER_HISTORY_FILE = "data/optimizer_history.json"

# ==================== HORÁRIO DE OPERAÇÃO ====================
TIMEFRAME_MT5 = mt5.TIMEFRAME_M5
START_TIME = datetime.time(10, 10)
END_TIME = datetime.time(16, 45)
CHECK_INTERVAL_SLOW = 8

# ==================== REGIME DE MERCADO ====================
USE_ML_REGIME = True
ML_MODEL_PATH = "models/regime_xgboost_2025.pkl"
IBOV_SYMBOL = None
#ENABLE_CIRCUIT_BREAKER = False

# ==================== FILTRO DE LIQUIDEZ ====================
MIN_ADV_20D_BRL = 8_000_000
MIN_VOLUME_5MIN_RATIO = 0.018
MAX_SPREAD_PCT = 0.16
MIN_BOOK_DEPTH_CONTRACTS = 600

# ==================== GESTÃO DE RISCO AVANÇADA ====================
MAX_TOTAL_DRAWDOWN_PCT = 0.12
MAX_EXPOSURE_PCT = 0.45
MAX_POSITIONS = 10
MAX_POSITIONS_PER_SECTOR = 2
COMISSAO_POR_LOTE = 0.05
SLIPPAGE_TICKS_MEDIO = 2.6
TARGET_VOL_ANNUAL = 0.20
MAX_DAILY_DRAWDOWN_PERCENT = 3.0
CLOSE_ON_DRAWDOWN_FACTOR = 1.0
CLOSE_POSITIONS_ON_CB = True
# Permitir operar fora do horário de mercado
ALLOW_OUTSIDE_MARKET_HOURS = True

VAR_95_DAILY_LIMIT = 0.025
MAX_TRADES_PER_CYCLE = 2

# ==================== OTIMIZAÇÃO ====================
PARAMS_STRONG_BULL = "params_strong_bull.json"
PARAMS_BULL = "params_bull.json"
PARAMS_SIDEWAYS = "params_sideways.json"
PARAMS_BEAR = "params_bear.json"
PARAMS_CRISIS = "params_crisis.json"

DEFAULT_PARAMS = {
    "regime": "DEFAULT",
    "sharpe_medio": 0.0,
    "side": "COMPRA",
    "ema_fast": 12,
    "ema_slow": 26,
    "rsi_level": 60,
    "momentum_min_pct": 0.4,
    "adx_min": 25,
    "sl_atr_mult": 2.0,
    "tp_atr_mult": 4.0,
    "trailing_mult": 1.5,
    "data": "N/A"
}

MAX_PER_SECTOR = 2
MAX_POSITIONS_TOTAL = 10

# ==================== LOGGING / METRICS ====================
ENABLE_METRICS = True
METRICS_PUSH_INTERVAL = 30  # segundos para gravar métricas locais

# ==================== UNIVERSO DE ATIVOS B3 (EXEMPLO) ====================
# Utilizado para o Scan de Oportunidades no bot.py
SYMBOL_MAP = {
    # 1. FINANCEIRO & SEGUROS (20)
    "ITUB4":"FINANCIALS", "BBDC4":"FINANCIALS", "BBAS3":"FINANCIALS", "SANB11":"FINANCIALS", 
    "B3SA3":"FINANCIALS", "BPAC11":"FINANCIALS", "CXSE3":"FINANCIALS", "BPAN4":"FINANCIALS",
    "BTG11":"FINANCIALS", "CIEL3":"FINANCIALS", "PSSA3":"FINANCIALS", "SULA11":"FINANCIALS", 
    "IRBR3":"FINANCIALS", "MERC3":"FINANCIALS", "BRSR6":"FINANCIALS", "BBSA3":"FINANCIALS",
    "WIZC3":"FINANCIALS", "SEQL3":"CDISCRETIONARY", "ODPV3":"CDISCRETIONARY", "CASH3":"CDISCRETIONARY", 
    
    # 2. COMMODITIES & MATERIAIS BÁSICOS (16)
    "VALE3":"MATERIALS", "CSNA3":"MATERIALS", "GGBR4":"MATERIALS", "USIM5":"MATERIALS", 
    "BRKM5":"MATERIALS", "KLBN11":"MATERIALS", "SUZB3":"MATERIALS", "BRAP4":"MATERIALS",
    "CMIN3":"MATERIALS", "GOAU4":"MATERIALS", "FESA4":"MATERIALS", "TGMA3":"INDUSTRIALS",
    "SLCE3":"STAPLES", "JBSS3":"STAPLES", "AZUL4":"INDUSTRIALS", "GOLL4":"INDUSTRIALS",

    # 3. ENERGIA & UTILITIES (16)
    "PETR4":"ENERGY", "PETR3":"ENERGY", "PRIO3":"ENERGY", "ENEV3":"ENERGY", 
    "ELET3":"UTILITIES", "CMIG4":"UTILITIES", "EQTL3":"UTILITIES", "CPFE3":"UTILITIES", 
    "TAEE11":"UTILITIES", "SABESP3":"UTILITIES", "ENBR3":"UTILITIES", "RECV3":"ENERGY",
    "RRRP3":"ENERGY", "ENAT3":"ENERGY", "CSAN3":"ENERGY", "ALUP11":"UTILITIES", 
    
    # 4. CONSUMO, VAREJO & INDÚSTRIA (24)
    "ABEV3":"STAPLES", "ASAI3":"STAPLES", "BEEF3":"STAPLES", "MRFG3":"STAPLES", "MDIA3":"STAPLES",
    "LREN3":"CDISCRETIONARY", "MGLU3":"CDISCRETIONARY", "ARZZ3":"CDISCRETIONARY", 
    "CVCB3":"CDISCRETIONARY", "SOMA3":"CDISCRETIONARY", "ALPA4":"CDISCRETIONARY",
    "YDUQ3":"CDISCRETIONARY", "COGN3":"CDISCRETIONARY", "PETZ3":"CDISCRETIONARY",
    "VVAR3":"CDISCRETIONARY", "RENT3":"INDUSTRIALS", "WEGE3":"INDUSTRIALS", "RAIL3":"INDUSTRIALS",
    "EMBR3":"INDUSTRIALS", "TEND3":"CDISCRETIONARY", "JALL3":"STAPLES", "LCAM3":"INDUSTRIALS",
    "LOGG3":"INDUSTRIALS", "MRVE3":"REALESTATE",

    # 5. SAÚDE, TECNOLOGIA & IMOBILIÁRIO (24)
    "RADL3":"HEALTHCARE", "AALR3":"HEALTHCARE", "PARD3":"HEALTHCARE", "QUAL3":"HEALTHCARE",
    "HYPE3":"HEALTHCARE", "RDOR3":"HEALTHCARE", "FLRY3":"HEALTHCARE", "TOTS3":"TECHNOLOGY", 
    "LWSA3":"TECHNOLOGY", "INTB3":"TECHNOLOGY", "VIVT3":"COMMUNICATION", "TIMS3":"COMMUNICATION", 
    "MYPK3":"INDUSTRIALS", "ANIM3":"CDISCRETIONARY", "POSI3":"TECHNOLOGY", "CYRE3":"REALESTATE", 
    "EZTC3":"REALESTATE", "JHSF3":"REALESTATE", "DIRR3":"REALESTATE", "EVEN3":"REALESTATE",
    "CAML3":"STAPLES", "GFSA3":"REALESTATE", "MOVI3":"INDUSTRIALS", "JPSA3":"CDISCRETIONARY"
}
